spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_loft
    username: Admin
    password: password
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true


loft:
  api:
    url: http://api.nbp.pl/api/exchangerates/rates/c/{code}?format=json